config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:show, :edit, :update] do
      get   "unsubscribe" => "users#unsubscribe"
      patch "withdrawal"  => "users#withdrawal"
      resources :favorites, only: [:index]
      resource  :matchings, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :posts do
      resource  :favorites, only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
      get "draft" => "posts#draft"
    end
    resources :rooms, only: [:create, :index, :show]
    resources :chats, only: [:create]
  end

  # 管理者用ルーティング
  namespace :admin do
    get "/search_user" => "searches#search_user"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags,  only: [:index, :destroy]
    resources :rooms, only: [:index, :show, :destroy]
  end

  # ゲストユーザー用ルーティング
  devise_scope :user do
    post "users/guest_sign_in",  to: "users/sessions#guest_sign_in"
    post "users/guest_sign_out", to: "users/sessions#guest_sign_out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many   :user_rooms, dependent: :destroy
  has_many   :chats,      dependent: :destroy
  has_many   :users,      through: :user_rooms
  belongs_to :post
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  def index
    @rooms = Room.order(created_at: :desc).page(params[:page])

    # 投稿に関連するチャット一覧
    if params[:post_id]
      @rooms = Room.where(post_id: params[:post_id]).order(created_at: :desc).page(params[:page])
    end
  end

  def show
    @room = Room.find(params[:id])
    @chats = @room.chats

    # 退会済ユーザーの情報を取得し、チャット画面上部に表示（最大２名）
    user_ids = @room.user_rooms.pluck(:user_id)
    users = User.where(id: user_ids).where(is_deleted: true)
    user_names = users.pluck(:display_name)
    if users.present?
      if users.count == 2
        flash.now[:info] = "#{user_names[0]}, #{user_names[1]}は退会済のユーザーです"
      else
        flash.now[:info] = "#{user_names[0]}は退会済のユーザーです"
      end
    end
  end

  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to admin_rooms_path, danger: "ルームを削除しました"
    end
  end

  private
    def room_params
      params.require(:room).permit(:post_id)
    end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/views/admin/rooms/_pagination.html.erb
<div class="pagination justify-content-center">
  <%= paginate rooms %>
</div>

app/views/admin/rooms/_room_list.html.erb
<% if rooms.present? %>
  <table class="table-responsive text-center text-nowrap w-100" style="table-layout: fixed;">
    <thead>
      <tr class="table table-secondary">
        <th scope="col" width="20%">投稿者</th>
        <th scope="col" width="20%">タイトル</th>
        <th scope="col">メッセージ</th>
        <th scope="col" width="15%"></th>
      </tr>
    </thead>
    <tbody>
      <% rooms.each do |room| %>
      <tr class="border-bottom">
        <td>
          <%= link_to admin_room_path(room.id) do %>
            <%= image_tag room.post.user.get_profile_image(100, 100), class: "RoomUserImg" %><br>
            <%= room.post.user.display_name %>
          <% end %>
        </td>
        <td>
          <strong><%= room.post.title %></strong>
        </td>
        <td>
          <% if room.chats.present? %>
            <% chat = Chat.find_by(id: room.chat_ids.last).message %>
            <%= truncate(chat, length: 30) %>
          <% else %>
            <p class="my-5">チャットを始めましょう</p>
          <% end %>
        </td>
        <td>
          <h6 style="color: #C0C0C0;"><%= room.updated_at.strftime("%Y/%m/%d %H:%M") %></h6>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-center my-5">チャットが見つかりませんでした</p>
<% end %>

app/views/admin/rooms/_search_room.html.erb
<!--ルーム検索欄-->
<div class="SearchRoomForm mr-3">
  <%= form_with url: admin_search_room_path, method: :get do |f| %>
    <%= f.text_field :search_room, placeholder: "キーワードを入力" %>
    <%= f.select :range, options_for_select([["ユーザー"], ["タイトル"]]) %>
    <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
  <% end %>
</div>

app/views/admin/rooms/index.html.erb
<!--ルーム一覧-->
<div class="container-fluid w-75 my-3">
  <div class="SearchForm d-inline-flex justify-content-end w-100">
    <%= render "search_room" %>
  </div>
  <div class="RoomList">
    <h2 class="font-weight-bold"><i class="fas fa-comments"></i> チャット一覧</h2>
    <%= render "room_list",  rooms: @rooms %>
    <%= render "pagination", rooms: @rooms %>
  </div>
</div>

app/views/admin/rooms/show.html.erb
<!--ルーム詳細-->
<div class="container-fluid w-100 py-3" style="background-color: #c1e4e9;">
  <div class="RoomBtn text-right">
    <%= link_to "削除", admin_room_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
  </div>
  <div class="RoomTitle text-center py-3">
    <h2><u><%= link_to "#{@room.post.title}", admin_post_path(@room.post) %></u></h2>
  </div>
  
  <!--チャットメッセージ-->
  <div id="chats">
    <%= render "admin/chats/chat_list", chats: @chats %>
  </div>
</div>