config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:show, :edit, :update] do
      get   "unsubscribe" => "users#unsubscribe"
      patch "withdrawal"  => "users#withdrawal"
      resources :favorites, only: [:index]
      resource  :matchings, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :posts do
      resource  :favorites, only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
      get "draft" => "posts#draft"
    end
    resources :rooms, only: [:create, :index, :show]
    resources :chats, only: [:create]
  end

  # 管理者用ルーティング
  namespace :admin do
    get "/search_user" => "searches#search_user"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags,  only: [:index, :destroy]
    resources :rooms, only: [:index, :show, :destroy]
  end

  # ゲストユーザー用ルーティング
  devise_scope :user do
    post "users/guest_sign_in",  to: "users/sessions#guest_sign_in"
    post "users/guest_sign_out", to: "users/sessions#guest_sign_out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  MAX_POST_TAGS_COUNT = 5

  belongs_to :user
  has_many   :rooms,         dependent: :destroy
  has_many   :notifications, dependent: :destroy
  has_many   :favorites,     dependent: :destroy
  has_many   :comments,      dependent: :destroy
  has_many   :post_tags,     dependent: :destroy
  has_many   :tags,          through: :post_tags, dependent: :destroy

  has_one_attached :image

  validates :title,       presence: true
  validates :since_when,  presence: true
  validates :at_where,    presence: true
  validates :for_playing, presence: true
  validates :body,        presence: true

  # 投稿の公開・非公開を設定
  enum status: { public: 0, private: 1 }, _prefix: true

  # 投稿のタグ保存/更新
  def save_tags(tag_data)
    posting_tags = tag_data.split(/[[:blank:]]+/)
    if posting_tags.count > MAX_POST_TAGS_COUNT
      errors.add(:base, "タグの数は最大#{MAX_POST_TAGS_COUNT}つまでです")
      return false
    end

    current_tags = self.tags.pluck(:name)

    old_tags = current_tags - posting_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags = posting_tags - current_tags
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end

    true
  end

  # 投稿データからステータスが公開でアクティブなユーザを取得、タグ検索用にtagsも結合
  def self.list(tag_id, page, user_id)
    posts = status_public.left_joins(:user).where(user: { is_deleted: false })

    if tag_id.present?
      posts = posts.left_joins(:tags).where(tags: { id: tag_id })
    end
    if user_id.present?
      posts = posts.where(user_id: user_id)
    end

    posts = posts.order(created_at: :desc).page(page)
    posts
  end

  # デフォルト画像の設定、サイズの指定
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image_square.jpeg")
      image.attach(io: File.open(file_path), filename: "default-sports-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize: "#{width}x#{height}^").processed
  end

  # いいねされているか確認
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # キーワード検索（部分一致）
  def self.search_word(search_word)
    @post = Post.where("title LIKE? OR body LIKE? OR at_where LIKE?",
    "%#{search_word}%", "%#{search_word}%", "%#{search_word}%").order(created_at: :desc)
  end

  # いいね通知の作成（投稿に対して自分以外のユーザーから初めていいねされた場合）
  def create_notification_favorite!(current_user)
    temp_favorite = Notification.where(["sender_id = ? and receiver_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, "favorite"])
    if temp_favorite.blank?
      notification = current_user.active_notifications.new(post_id: id, receiver_id: user_id, action: "favorite")
      notification.checked = true if notification.sender_id == notification.receiver_id
      notification.save if notification.valid?
    end
  end

  # コメント通知の作成
  def create_notification_comment!(current_user, comment_id)
    # 投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) unless current_user.id == user_id
    # 自分以外のコメント投稿者に通知を送る
    temp_users = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_users.each do |temp_user|
      save_notification_comment!(current_user, comment_id, temp_user["user_id"])
    end
  end

  def save_notification_comment!(current_user, comment_id, receiver_id)
    notification = current_user.active_notifications.new(post_id: id, comment_id: comment_id, receiver_id: receiver_id, action: "comment")
    notification.checked = true if notification.sender_id == notification.receiver_id
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  # 投稿データからステータスが公開でアクティブなユーザを取得、タグ検索用にtagsも結合
  def index
    @posts = Post.list(params[:tag_id], params[:page], params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params) && @post.save_tags(params[:post][:tag])
      redirect_to admin_post_path(@post.id), success: "投稿を更新しました"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path, danger: "投稿を削除しました"
    end
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :title, :body, :since_when, :at_where, :for_playing, :image)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_pagination.html.erb
<!--投稿一覧のページネーション-->
<div class="pagination justify-content-center">
  <%= paginate posts %>
</div>

app/views/admin/posts/_post_list.html.erb
<% if posts.present? %>
  <table class="table table-bordered table-responsive-md text-center text-nowrap" style="table-layout: fixed;">
    <tr class="table table-secondary">
      <th scope="col" width="10%"></th>
      <th scope="col">投稿者</th>
      <th scope="col">タイトル</th>
      <th scope="col">タグ</th>
      <th scope="col">日時</th>
      <th scope="col">場所</th>
      <th scope="col" width="7%">いいね</th>
      <th scope="col" width="8%">コメント</th>
      <th scope="col" width="6%"></th>
    </tr>
    <% posts.each do |post| %>
    <tr>
      <td><%= image_tag post.get_image(100, 100), class: "PostIndexImg" %></td>
      <td><%= post.user.display_name %></td>
      <td><%= post.title %></td>
      <td>
        <% post.tags.each do |tag| %>
          <%= link_to admin_posts_path(tag_id: tag.id), class: "Tag" do %>
            <h7><small>#<%= tag.name %></small></h7>
          <% end %>
        <% end %>
      </td>
      <td><%= post.since_when.strftime("%Y/%m/%d %H:%M") %></td>
      <td><%= post.at_where %></td>
      <td style="color: red">♥<%= post.favorites.count %></td>
      <td><%= post.comments.count %>件</td>
      <td><%= link_to "詳細", admin_post_path(post.id) %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p class="text-center my-5">投稿が見つかりませんでした</p>
<% end %>

app/views/admin/posts/_posts_table.html.erb
<!--投稿一覧テーブル-->
<% if posts.present? %>
  <table class="table table-bordered text-center" style="table-layout: fixed;">
    <tr class="table table-secondary">
      <th scope="col" width="10%"></th>
      <th scope="col">投稿者</th>
      <th scope="col">タイトル</th>
      <th scope="col">タグ</th>
      <th scope="col">日時</th>
      <th scope="col">場所</th>
      <th scope="col" width="7%">いいね</th>
      <th scope="col" width="8%">コメント</th>
      <th scope="col" width="5%"></th>
    </tr>
    <% posts.each do |post| %>
    <tr>
      <td><%= image_tag post.get_image(100, 100) %></td>
      <td><%= post.user.display_name %></td>
      <td><%= post.title %></td>
      <td>
        <% post.tags.each do |tag| %>
          <%= link_to admin_posts_path(tag_id: tag.id), class: "Tag" do %>
            <h7><small>#<%= tag.name %></small></h7>
          <% end %>
        <% end %>
      </td>
      <td><%= post.since_when.strftime("%Y/%m/%d %H:%M") %></td>
      <td><%= post.at_where %></td>
      <td style="color: red">♥<%= post.favorites.count %></td>
      <td><%= post.comments.count %>件</td>
      <td><%= link_to "詳細", admin_post_path(post.id) %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p class="text-center my-5">投稿が見つかりませんでした</p>
<% end %>

app/views/admin/posts/_search_tag.html.erb
<!--タグ検索欄-->
<div class="SearchTagForm">
  <!--特定のユーザーの投稿履歴からタグ検索する場合-->
  <% if params[:user_id] %>
    <%= form_with url: admin_posts_path, method: :get do |f| %>
      <%= f.select :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]), { prompt: "タグ検索" } %>
      <%= f.hidden_field :user_id, value: params[:user_id] %>
      <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
    <% end %>
  <% else %>
  <!--通常のタグ検索-->
    <%= form_with url: admin_posts_path, method: :get do |f| %>
      <%= f.select :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]), { prompt: "タグ検索" } %>
      <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
    <% end %>
  <% end %>
</div>

app/views/admin/posts/_search_word.html.erb
<!--キーワード検索欄-->
<div class="SearchWordForm mr-3">
  <%= form_with url: admin_search_post_path, method: :get do |f| %>
    <%= f.text_field :search_word, placeholder: "キーワードを入力" %>
    <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
  <% end %>
</div>

app/views/admin/posts/edit.html.erb
<!--バリデーションエラー-->
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました。
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!--投稿編集-->
<div class="container-fluid w-75 my-3">
  <h2 class="font-weight-bold"><i class="fas fa-edit"></i> 投稿編集</h2>
  <div class="PostForm">
    <%= form_with model: [:admin, @post] do |f| %>
      <div class="form-group">
        <%= f.label :"イメージ画像" %><br>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div id="preview-img"></div>
      <div class="form-group">
        <%= f.label :"タグ ※スペース区切りで5つまで" %><br>
        <%= f.text_field :tag, value: @post.tags.pluck(:name), placeholder: "野球 キャッチボール 初心者", class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.label :"タイトル" %>
        <%= f.text_field :title, placeholder: "キャッチボール", class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.label :"日時" %>
        <%= f.datetime_field :since_when, class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.label :"場所" %>
        <%= f.text_field :at_where, placeholder: "テスト公園", class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.label :"持ち物" %>
        <%= f.text_field :for_playing, placeholder: "グローブ", class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.label :"詳細情報" %>
        <%= f.text_area :body, placeholder: "宜しくお願いします", class: "form-control col-sm-6" %>
      </div>
      <div class="form-group">
        <%= f.radio_button :status, :public %>
        <%= f.label :status_public, "公開" %><br>
        <%= f.radio_button :status, :private %>
        <%= f.label :status_private, "非公開（下書き）" %>
      </div>
      <%= f.submit "変更を保存する", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<!--投稿一覧-->
<div class="container-fluid w-75 my-3">
  <div class="SearchForm d-inline-flex justify-content-end w-100">
    <%= render "search_word" %>
    <%= render "search_tag" %>
  </div>

  <div class="PostList">
    <h2 class="font-weight-bold"><i class="fas fa-list"></i> 投稿一覧</h2>
    <%= render "post_list",  posts: @posts %>
    <%= render "pagination", posts: @posts %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<!--投稿詳細-->
<div class="container-fluid w-75 my-3">
  <div class="PostListMenu d-inline-flex justify-content-between w-100">
    <h2 class="font-weight-bold"><i class="fas fa-file"></i> 投稿詳細</h2>
    <div class="PostBtn">
      <%= link_to "編集", edit_admin_post_path(@post.id), class: "btn btn-success mr-4" %>
      <%= link_to "削除", admin_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
    </div>
  </div>
  
  <!--投稿情報①-->
  <div class="row mt-3">
    <div class="PostLeft col-4 text-center">
      <div class="PostImage border-bottom"><br>
        <%= image_tag @post.get_image(200, 200), class: "img-fluid PostShowImg" %>
        <div style="color: red">♥<%= @post.favorites.count %></div>
        <% @post.tags.each do |tag| %>
          <%= link_to admin_posts_path(tag_id: tag.id), class: "Tag" do %>
            <h7><small>#<%= tag.name %></small></h7>
          <% end %>
        <% end %>
      </div>
      <div class="PostUser my-3">
        <p class="font-weight-bold mb-0">投稿者</p>
        <%= link_to admin_user_path(@user) do %>
          <%= image_tag @user.get_profile_image(120, 120), class: "img-fluid PostShowUserImg my-2" %><br>
          <%= @user.display_name %>
        <% end %>
      </div>
    </div>
    
    <!--投稿情報②-->
    <div class="PostRight col-8">
      <div class="PostStatus">
        <% if @post.status_public? %>
          <h6 class="text-success"><i class="fas fa-circle"></i><%= @post.status_i18n %></h6>
        <% else %>
          <h6 class="text-secondary"><i class="fas fa-circle"></i><%= @post.status_i18n %></h6>
        <% end %>
      </div>
      <table class="table table-bordered table-responsive-sm text-nowrap">
        <tr>
          <th scope="row" class="table-secondary" style="width: 20%">タイトル</th>
          <td><%= @post.title %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">日時</th>
          <td><%= @post.since_when.strftime("%Y/%m/%d %H:%M") %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">場所</th>
          <td><%= @post.at_where %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">持ち物</th>
          <td><%= @post.for_playing %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">詳細情報</th>
          <td><%= simple_format(h(@post.body))%></td>
        </tr>
      </table>
      
      <div class="RoomsPerPost text-right">
        <%= link_to "関連するチャット一覧", admin_rooms_path(post_id: @post.id), class: "btn btn-primary" %>
      </div>
      
      <!--コメント一覧-->
      <div id="comment">
        <%= render "admin/comments/comment_list", post: @post %>
      </div>
    </div>
  </div>
</div>