config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:show, :edit, :update] do
      get   "unsubscribe" => "users#unsubscribe"
      patch "withdrawal"  => "users#withdrawal"
      resources :favorites, only: [:index]
      resource  :matchings, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :posts do
      resource  :favorites, only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
      get "draft" => "posts#draft"
    end
    resources :rooms, only: [:create, :index, :show]
    resources :chats, only: [:create]
  end

  # 管理者用ルーティング
  namespace :admin do
    get "/search_user" => "searches#search_user"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags,  only: [:index, :destroy]
    resources :rooms, only: [:index, :show, :destroy]
  end

  # ゲストユーザー用ルーティング
  devise_scope :user do
    post "users/guest_sign_in",  to: "users/sessions#guest_sign_in"
    post "users/guest_sign_out", to: "users/sessions#guest_sign_out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :posts,                 dependent: :destroy
  has_many :favorites,             dependent: :destroy
  has_many :comments,              dependent: :destroy
  has_many :matchings,             class_name: "Matching",         foreign_key: "follower_id",  dependent: :destroy
  has_many :reverse_of_matchings,  class_name: "Matching",         foreign_key: "following_id", dependent: :destroy
  has_many :followings,            through: :matchings,            source: :following
  has_many :followers,             through: :reverse_of_matchings, source: :follower
  has_many :user_rooms,            dependent: :destroy
  has_many :rooms,                 through: :user_rooms
  has_many :chats
  has_many :active_notifications,  class_name: "Notification",     foreign_key: "sender_id",    dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",     foreign_key: "receiver_id",  dependent: :destroy

  has_one_attached :profile_image

  validates :display_name,     presence: true
  validates :name,             presence: true
  validates :telephone_number, presence: true, uniqueness: true, numericality: { only_integer: true }, length: { in: 10..11 }
  validates :email,            presence: true, uniqueness: true
  validates :password,         on: :create,    presence: true,   length: { in: 6..128 }

  # デフォルト画像の設定、サイズの指定
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpeg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize: "#{width}x#{height}^").processed
  end

  # 退会ステータスのユーザーをログインさせない
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  # ユーザー検索（管理者画面）
  def self.search_user(search_user)
    @user = User.where("name LIKE? OR display_name LIKE?", "%#{search_user}%", "%#{search_user}%")
  end

  # ゲストユーザーのログイン情報
  def self.guest
    find_or_create_by!(display_name: "ゲストユーザー", name: "guestuser", telephone_number: "00000000000", email: "guest@example.com") do |guest_user|
      guest_user.password = SecureRandom.urlsafe_base64
    end
  end

  # フォローする（マッチングする）
  def follow(user_id)
    matchings.create(following_id: user_id)
  end

  # フォローを外す（マッチングを解除する）
  def unfollow(user_id)
    matchings.find_by(following_id: user_id).destroy
  end

  # フォロー（マッチング）判定
  def following?(user)
    followings.include?(user)
  end

  # フォロー（マッチング）通知の作成
  def create_notification_follow!(current_user)
    temp = Notification.where(["sender_id = ? and receiver_id = ? and action = ?", current_user.id, id, "follow"])
    if temp.blank?
      notification = current_user.active_notifications.new(receiver_id: id, action: "follow")
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), success: "ユーザー情報を更新しました"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :prefecture, :municipality, :telephone_number, :display_name, :self_introduction, :is_deleted, :profile_image)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    guest_user = User.guest
    sign_in guest_user
    redirect_to posts_path, notice: "ゲストユーザーでログインしました"
  end

  def guest_sign_out
    guest_user = User.guest
    sign_out guest_user
    redirect_to root_path, notice: "ゲストユーザーからログアウトしました"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_pagination.html.erb
<!--ユーザー一覧のページネーション-->
<div class="pagination justify-content-center">
  <%= paginate users %>
</div>

app/views/admin/users/_search_user.html.erb
<!--ユーザー検索欄-->
<div class="SearchUserForm">
  <%= form_with url: admin_search_user_path, method: :get do |f| %>
    <%= f.text_field :search_user, placeholder: "ユーザー名or氏名を入力" %>
    <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
  <% end %>
</div>

app/views/admin/users/_user_list.html.erb
<% if users.present? %>
  <table class="table table-bordered table-responsive-lg text-center text-nowrap">
    <tr class="table table-secondary">
      <th scope="col"></th>
      <th scope="col">ID</th>
      <th scope="col">ステータス</th>
      <th scope="col">ユーザー名</th>
      <th scope="col">都道府県</th>
      <th scope="col">市区町村</th>
      <th scope="col"></th>
    </tr>
    <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100, 100), class: "UserIndexImg" %></td>
      <td><%= user.id %></td>
      <td><%= user.is_deleted ? "退会" : "有効" %></td>
      <td><%= user.display_name %></td>
      <td><%= user.prefecture %></td>
      <td><%= user.municipality %></td>
      <td><%= link_to "詳細", admin_user_path(user.id) %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p class="text-center my-5">ユーザーが見つかりませんでした</p>
<% end %>

app/views/admin/users/edit.html.erb
<!--バリデーションエラー-->
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました。
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!--ユーザー編集-->
<div class="container my-3">
  <div class="UserForm">
    <h2 class="font-weight-bold"><i class="fas fa-user-edit"></i> ユーザー編集</h2>
    <div class="row d-block">
      <div class="col-6">
        <%= form_with model: [:admin, @user] do |f| %>
          <div class="form-group">
            <%= f.label :"プロフィール画像" %><br>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>
          <div class="form-group">
            <%= f.label :"氏名" %>
            <%= f.text_field :name, placeholder: "佐藤太郎", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"電話番号" %>
            <%= f.text_field :telephone_number, placeholder: "00000000000", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"メールアドレス" %>
            <%= f.text_field :email, placeholder: "test@example.com", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"ユーザー名" %>
            <%= f.text_field :display_name, placeholder: "テスト太郎", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"都道府県" %>
            <%= f.text_field :prefecture, placeholder: "東京都", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"市区町村" %>
            <%= f.text_field :municipality, placeholder: "新宿区", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"自己紹介" %>
            <%= f.text_area :self_introduction, placeholder: "宜しくお願いします", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted_false, "有効" %><br>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted_true, "退会" %>
          </div>
          <%= f.submit "変更を保存する", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<!--ユーザー一覧-->
<div class="container-fluid w-75 my-3">
  <div class="SearchForm d-flex justify-content-end w-100">
    <%= render "search_user" %>
  </div>
  
  <div class="UserList">
    <h2 class="font-weight-bold"><i class="fas fa-users"></i> ユーザー一覧</h2>
    <%= render "admin/users/user_list",  users: @users %>
    <%= render "admin/users/pagination", users: @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<!--ユーザー詳細-->
<div class="container mt-3">
  <h2 class="font-weight-bold"><i class="fas fa-user"></i> ユーザー詳細</h2>
  <div class="UserBtn">
    <div class="UserBtn text-right">
      <%= link_to "編集", edit_admin_user_path(@user.id), class: "btn btn-success" %>
    </div>
  </div>
  
  <div class="UserImg">
    <div class="text-center">
      <%= image_tag @user.get_profile_image(300, 300), class: "UserShowImg my-2" %>
    </div>
  </div>
  
  <div class="UserInfo row">
    <div class="col-4">
      <table class="table table-bordered table-responsive-lg text-nowrap">
        <tr>
          <th scope="row" class="table-secondary">氏名</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">電話番号</th>
          <td><%= @user.telephone_number %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
      </table>
    </div>
    <div class="col-8">
      <table class="table table-bordered">
        <tr>
          <th scope="row" class="table-secondary">ID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">ステータス</th>
          <td><%= @user.is_deleted ? "退会" : "有効" %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">ユーザー名</th>
          <td><%= @user.display_name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">都道府県</th>
          <td><%= @user.prefecture %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">市区町村</th>
          <td><%= @user.municipality %></td>
        </tr>
        <tr>
          <th scope="row" class="table-secondary">自己紹介</th>
          <td><%= simple_format(h(@user.self_introduction)) %></td>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="UserPosted">
    <div class="text-right">
      <p><%= link_to admin_posts_path(user_id: @user.id) do %><u>過去の投稿</u><% end %></p>
    </div>
  </div>
</div>