config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:show, :edit, :update] do
      get   "unsubscribe" => "users#unsubscribe"
      patch "withdrawal"  => "users#withdrawal"
      resources :favorites, only: [:index]
      resource  :matchings, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :posts do
      resource  :favorites, only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
      get "draft" => "posts#draft"
    end
    resources :rooms, only: [:create, :index, :show]
    resources :chats, only: [:create]
  end

  # 管理者用ルーティング
  namespace :admin do
    get "/search_user" => "searches#search_user"
    get "/search_post" => "searches#search_post"
    get "/search_room" => "searches#search_room"
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags,  only: [:index, :destroy]
    resources :rooms, only: [:index, :show, :destroy]
  end

  # ゲストユーザー用ルーティング
  devise_scope :user do
    post "users/guest_sign_in",  to: "users/sessions#guest_sign_in"
    post "users/guest_sign_out", to: "users/sessions#guest_sign_out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<!--フラッシュメッセージ（Bootstrapのalertを適用）-->
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key} mb-0") %>
<% end %>

app/views/layouts/_footer.html.erb
<!--フッター-->
<footer class="d-flex align-items-center justify-content-center">
  <h6 class="mb-0">©️︎TBan34</h6>
</footer>

app/views/layouts/_header.html.erb
<!--ヘッダー-->
<header> 
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #365E94">
    <div class="container-fluid">
      <!--ヘッダー左（※管理者ログイン時はロゴのリンクなし）-->
      <a class="navbar-brand ml-5" href="/">
        <% if admin_signed_in? %>
          <%= image_tag "ones-community-logo.png", class: "img-fluid", size: "100x100" %>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag asset_path("ones-community-logo.png"), class: "img-fluid", size: "100x100" %>
          <% end %>
        <% end %>
      </a>
      <!--ヘッダー右-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto mr-5">
          <!--ユーザー/ゲストユーザーログイン時-->
          <% if user_signed_in? %>
            <% if current_user != User.guest %>
              <li class="nav-item ml-3">
                <%= link_to current_user, class: "btn btn-outline-light" do %>
                  <i class="fas fa-user"></i>マイページ
                <% end %>
              </li>
            <% end %>
            <li class="nav-item ml-3">
              <%= link_to about_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-key"></i>About
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to posts_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to rooms_path(user_id: current_user.id), class: "btn btn-outline-light" do %>
                <i class="fas fa-comments"></i>チャット一覧
              <% end %>
            </li>
            <% if current_user != User.guest %>
              <li class="nav-item ml-3">
                <%= link_to destroy_user_session_path, class: "btn btn-outline-light", method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item ml-3">
                <%= link_to users_guest_sign_out_path, class: "btn btn-outline-light", method: :post do %>
                  <i class="fas fa-sign-out-alt"></i>ゲストログアウト
                <% end %>
              </li>
            <% end %>
          <!--管理者ログイン時-->
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_users_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_posts_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_rooms_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-comments"></i>チャット一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_tags_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-tags"></i>タグ一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to destroy_admin_session_path, class: "btn btn-outline-light", method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          <!--未ログイン時-->
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to new_user_session_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to about_path, class: "btn btn-outline-light" do %>
                <i class="fas fa-key"></i>About
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One's Community</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f5f5f5;">
    <div class="FixedFooterBottom">
      <%= render "layouts/header" %>
      <div id="flash_message">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>